<div id="interior-nav">
   <ul><!-- com.omniupdate.div group="Everyone" label="/zz-sidenav.inc" button="768" path="/zz-sidenav.inc"--><?php include($_SERVER['DOCUMENT_ROOT'] . "/zz-sidenav.inc");
				?><!-- /com.omniupdate.div --><li>
         <a href="/test/index.php">Test</a>
         <div class="submenu">
            <ul><!-- com.omniupdate.div group="Everyone" label="/test/zz-sidenav.inc" button="768" path="/test/zz-sidenav.inc"--><?php include($_SERVER['DOCUMENT_ROOT'] . "/test/zz-sidenav.inc");
				?><!-- /com.omniupdate.div --></ul>
         </div>
      </li>
   </ul>
</div>